### PR TITLE
Add 'infc_malinalli_k9.map'

### PR DESCRIPTION
**Pull request by TheVayt**
Feedback is welcome

### CODE REVIEW

**Comment by bretonium** [comment]
This is good, but please also add it to `sv_maprotation` in `/src/game/variables.h`

**Comment by Kaffeine** [comment]
@bretonium What is the reason to add every map to the rotation list? It is a single line that breaks git operations (rebase, revert, etc) and either way most of the hosters (including you, @bretonium AFAIK) maintain their own list in the server config file.

The map looks good :). Maybe add .mapinfo file with `timelimit` and `minplayers`?

@TheVayt see [infc_towers.mapinfo](https://github.com/bretonium/my-infclass-server/blob/e77ab12661d47a8eefc4dd4288a605000c32b780/bin/data/maps/infc_towers.mapinfo) for template.

**Comment by bretonium** [comment]
> @bretonium What is the reason to add every map to the rotation list? It is a single line that breaks git operations (rebase, revert, etc) and either way most of the hosters (including you, @bretonium AFAIK) maintain their own list in the server config file.

I expect that if someone decides to run a server, they will have something very close to what i have, by default. It also increases discoverability of maps for not experienced admins, and will let them use the new map if it appears here.

> most of the hosters maintain their own list in the server config file.

We don't know that. I knew at least one server that seemed to run the default version of this one, with almost no changes to config.

**Comment by bretonium** [comment]
ok ok i'll do it myself

**Pull request merged**
